package program.view;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

import program.controllers.UserLogic;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cassy McJack
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    
    ArrayList<JTextField> myFields = new ArrayList<>();
    public static MainView myMain;
    
    
    public RegisterView() {
        initComponents();
        gatherTF();
        jTextPane1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sucess = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF_Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_Password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_RepeatPass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FTF_Birthday = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CB_PC = new javax.swing.JCheckBox();
        CB_Switch = new javax.swing.JCheckBox();
        CB_PSP = new javax.swing.JCheckBox();
        CB_Mobile = new javax.swing.JCheckBox();
        CB_NES = new javax.swing.JCheckBox();
        CB_Ouya = new javax.swing.JCheckBox();
        CB_PS = new javax.swing.JCheckBox();
        CB_Stadia = new javax.swing.JCheckBox();
        CB_Xbox = new javax.swing.JCheckBox();
        ToS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Btn_Register = new javax.swing.JButton();
        label_State = new javax.swing.JLabel();

        Sucess.setMinimumSize(new java.awt.Dimension(311, 150));
        Sucess.setResizable(false);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Signed up suscessfully");

        javax.swing.GroupLayout SucessLayout = new javax.swing.GroupLayout(Sucess.getContentPane());
        Sucess.getContentPane().setLayout(SucessLayout);
        SucessLayout.setHorizontalGroup(
            SucessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SucessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SucessLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SucessLayout.setVerticalGroup(
            SucessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SucessLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register, please :)");
        setMinimumSize(new java.awt.Dimension(578, 429));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Sign up Data");
        Data.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 6, -1, -1));

        jLabel2.setText("Username");
        Data.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 63, -1));
        Data.add(TF_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 34, 196, -1));

        jLabel3.setText("E-Mail");
        Data.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));
        Data.add(TF_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 68, 196, -1));

        jLabel4.setText("Password");
        Data.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));
        Data.add(TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 108, 196, -1));

        jLabel5.setText("Repeat password");
        Data.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, -1, -1));
        Data.add(TF_RepeatPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 148, 196, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Personal Data");
        Data.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 182, -1, -1));

        jLabel8.setText("Day of birth");
        Data.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, -1, -1));

        FTF_Birthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        Data.add(FTF_Birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 210, 196, -1));

        jLabel9.setText("Used platforms");
        Data.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 244, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 0, 10));

        CB_PC.setText("PC");
        CB_PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_PCActionPerformed(evt);
            }
        });
        jPanel1.add(CB_PC);

        CB_Switch.setText("Switch");
        jPanel1.add(CB_Switch);

        CB_PSP.setText("PSP");
        CB_PSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_PSPActionPerformed(evt);
            }
        });
        jPanel1.add(CB_PSP);

        CB_Mobile.setText("Mobile");
        CB_Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_MobileActionPerformed(evt);
            }
        });
        jPanel1.add(CB_Mobile);

        CB_NES.setText("NES");
        CB_NES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_NESActionPerformed(evt);
            }
        });
        jPanel1.add(CB_NES);

        CB_Ouya.setText("Ouya");
        CB_Ouya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_OuyaActionPerformed(evt);
            }
        });
        jPanel1.add(CB_Ouya);

        CB_PS.setText("Play Station");
        jPanel1.add(CB_PS);

        CB_Stadia.setText("Stadia");
        CB_Stadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_StadiaActionPerformed(evt);
            }
        });
        jPanel1.add(CB_Stadia);

        CB_Xbox.setText("XBox");
        jPanel1.add(CB_Xbox);

        Data.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 280, 110));

        ToS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Terms of Service");
        ToS.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jTextPane1.setText("Desde Casandra Gamerwors no nos hacemos responsalbes de las distintas experiencas reveladoras que estais por tener, de las ideas revolucionarias que pueden salir de tu experiencia como jugador, o de tus desdes autolícitos por todo el caos. Esta es una vista directa al infierno que es la mente de la programadora princiapl, así que abróchese bien el cinturón, prepare pañuelos, un objeto afilado, y disfrute del viaje. Creando su cuenta, autoriza, además, el uso de sus datos en distinta caterba de rituales.");
        jScrollPane2.setViewportView(jTextPane1);

        ToS.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 221, 262));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 400));

        Btn_Register.setText("Sign up");
        Btn_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        label_State.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(label_State, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_StadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_StadiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_StadiaActionPerformed

    private void CB_OuyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_OuyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_OuyaActionPerformed

    private void CB_PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_PCActionPerformed

    private void CB_PSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_PSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_PSPActionPerformed

    private void CB_NESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_NESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_NESActionPerformed

    private void CB_MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_MobileActionPerformed

    private void Btn_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegisterActionPerformed
        // TODO add your handling code here:
        if(checkStatus()){
            if(UserLogic.RegisterUser(TF_Username.getText(), TF_Email.getText(), TF_Password.getText(), FTF_Birthday.getText())){
                myMain.setVisible(true);
                Sucess.setVisible(true);
                this.dispose();
            }else{
                label_State.setText("User already registed or incorrect data");
            }
        }else{
            label_State.setText("Fill all the fields in the right way");
        }
    }//GEN-LAST:event_Btn_RegisterActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        myMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }
    
    private void gatherTF(){
        for (Component component : Data.getComponents()) {
            if (component instanceof JTextField) {
                myFields.add((JTextField)component);
            }
        }
    }
    
    private boolean checkStatus(){
        boolean ready=true;
        
        for (JTextField tf : myFields) {
            if(tf.getText().equals("")){
                ready=false;
                tf.setBorder(new LineBorder(Color.red));
            }else{
                tf.setBorder(new LineBorder(Color.blue));
            }
        }
        
        return ready;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Register;
    private javax.swing.JCheckBox CB_Mobile;
    private javax.swing.JCheckBox CB_NES;
    private javax.swing.JCheckBox CB_Ouya;
    private javax.swing.JCheckBox CB_PC;
    private javax.swing.JCheckBox CB_PS;
    private javax.swing.JCheckBox CB_PSP;
    private javax.swing.JCheckBox CB_Stadia;
    private javax.swing.JCheckBox CB_Switch;
    private javax.swing.JCheckBox CB_Xbox;
    private javax.swing.JPanel Data;
    private javax.swing.JFormattedTextField FTF_Birthday;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JDialog Sucess;
    private javax.swing.JTextField TF_Email;
    private javax.swing.JTextField TF_Password;
    private javax.swing.JTextField TF_RepeatPass;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JPanel ToS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel label_State;
    // End of variables declaration//GEN-END:variables
}
